#!/bin/bash

set -eu

PYTHON=python3

DIR_NAME=$(dirname $(readlink -f $0))


[ ! -e $DIR_NAME/.venv/ok ] && {
	$PYTHON -m venv $DIR_NAME/.venv && touch $DIR_NAME/.venv/ok
}

source $DIR_NAME/.venv/bin/activate

[ ! -e $DIR_NAME/.requirements_installed ] && {
	pip install -r $DIR_NAME/requirements.txt && touch $DIR_NAME/.requirements_installed
}

python3 $DIR_NAME/src/ai.py $@

deactivate
