#!/bin/bash

set -eu

PYTHON=python3

if [ ! -d ~/.ai ]; then
	( umask 077 ~/.ai && mkdir ~/.ai )
fi

export DIR_NAME=$(dirname $(readlink -f $0))


[ ! -e ~/.ai/venv_ok ] && {
	$PYTHON -m venv $DIR_NAME/.venv && touch ~/.ai/venv_ok
	#$DIR_NAME/.venv/ok
}

source $DIR_NAME/.venv/bin/activate

[ ! -e  ~/.ai/requirements_ok ] && {
	pip install -r $DIR_NAME/requirements.txt && touch ~/.ai/requirements_ok
}

python3 $DIR_NAME/src/ai.py $@

deactivate
